version: '3'

services:
  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    image: ottogtz94/calcula-numero-nest:latest
    container_name: calcula-numero-nestjs-prod
    ports:
      - ${PORT}:3000
