version: '3'

services:
  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    container_name: calcula-numero-nestjs-dev
    ports:
      - ${PORT}:3000
